[Review] 백엔드 리뷰 재요청드립니다.
codesquad-member-2020/sidedish-07 pull request #78
Opened 2020-05-06 10:51 UTC by beginin15

구현 기능
- Github OAuth 로그인
- 각 메뉴 조회 API (main, soup, side)
- 상세 조회 API (detail)
- 주문하기 API (로그인 당시 발행한 jwt 토큰 활용)

궁금한 점
테이블 관계를 m:n으로 맵핑해주기 위해서 중간에 FK를 들고 있는 조인(?) 테이블을 생성하는 것이 일반적인 방법인가요? 이번 과제에서 Spring Data JDBC를 사용하면서 해당 테이블을 따로 생성해줬었는데 JPA의 @ManyToMany도 내부적으로는 비슷하게 작동하는건지 궁금했습니다!
코드 읽어주셔서 감사합니다!

2020-05-10 04:15 UTC, wheejuni requested changes
수고 많으셨습니다. 
간단한 수정사항 피드백 남겨드렸으니 확인해 주시고요. 

질문에 답변드리면 **그게 맞는 방법입니다. **
관계형 데이터베이스에선 그것 외에 다대다 관계를 표현할 방법이 없습니다. 

그리고 코멘트에 @ 사용하시면 사용자가 태그되니 늘 조심해주세요 ㅋㅋㅋ 회사에서도 가끔 이걸로 실수하시는 분들 있어요.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/api/LoginController.java
> +    private UserRepository userRepository;
`Controller` 에서 `Repository` 를 직접 받는 것은 사실 그렇게 좋진 않아요.
그리고 왜 한쪽에만 `final` 이 붙어 있을까요.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/api/SidedishController.java
> +    private UserRepository userRepository;
여기는 또 둘 다 `final` 이 안 붙어있네요.
혹시 다른 기준이 있으신 건지 궁금하네요.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/api/SidedishController.java
> +        }
`try-catch` 가 필요할 정도의 DAO 로직이라면 별도의 서비스 클래스가 있어야 할 것으로 보여져요.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/api/SidedishController.java
> +    }
컨트롤러에 있어야 할 로직일까요? 
각기 다른 책임을 하는 로직이 컨트롤러에 이렇게 하나씩 붙을 때마다 컨트롤러의 가독성은 -1 됩니다.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/dao/ProductDAO.java
> +                " CONCAT(FORMAT(p.s_price, 0), '원') AS s_price, CONCAT(FORMAT(p.n_price, 0), '원') AS n_price," +
`CONCAT` 같은 처리는 가능하면 애플리케이션 레이어로 끌고 와서 해주세요. 
배민도 베트남 법인이 있던데 나중에 해외진출하면 어떻게 되나요. 
항상 극단적인 확장성을 고려할 필요까진 없겠지만, 애플리케이션에서 처리할 수 있는 일들은 애플리케이션에게 맡기는 것이 좋습니다.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/dao/ProductDAO.java
> +                }
이정도 복잡성이라면 따로 `@Configuration` 클래스를 선언해서 거기서 빈으로 등록해주는 방법을 고려해보는 것도 좋을 듯 싶네요.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/dto/DetailDTO.java
> +    private Integer id;
`DTO` 클래스에서 `@JsonIgnore` 라면, 이 값이 꼭 필요한 필드인지도 고민해볼만 합니다. 
`DetailDTO` 객체에 `id` 가 있어야 하나요?

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/dto/DetailDTO.java
> +                     List<String> deliveryTypes) {
`Builder` 사용을 고려해주세요.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/entity/OAuthGithubToken.java
> +@Component
`Token` 인데 정말 `Component` 인가요?
컴포넌트로 관리해야 할 이유를 알고 싶어요.

2020-05-10 04:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish/initialization/SidedishApplicationRunner.java
> +    private static final String detailUrl = "https://h3rb9c0ugl.execute-api.ap-northeast-2.amazonaws.com/develop/baminchan/detail";
값들은 항상 `properties` 로 관리해 주시고요.

2020-05-19 08:53 UTC, honux77 commented on BE/src/main/java/com/codesquad/sidedish/api/SidedishController.java
> +    private UserRepository userRepository;
저도 궁금

2020-05-19 09:05 UTC, honux77 commented
두분 모두 수고하셨어요. 주말에 이전 PR도 한 번씩 보세요!

2020-05-19 09:05 UTC, merged

2020-05-19 09:16 UTC, beginin15 commented on BE/src/main/java/com/codesquad/sidedish/api/LoginController.java
> +    private UserRepository userRepository;
이 프로젝트 진행할 당시에는 `Service` 에 대한 개념이 잘 잡혀있지 않아서 제가 작업한 부분은 컨트롤러에서 로직을 처리해준 부분이 많았습니다. 최근에는 `Service` 클래스를 활용해서 해당 클래스에서 `Repository`에 접근하도록 작성하려고 노력하고 있습니다!

2020-05-19 09:20 UTC, beginin15 commented on BE/src/main/java/com/codesquad/sidedish/api/SidedishController.java
> +    private UserRepository userRepository;
페어랑 코드를 합칠 때 미처 확인하지 못한 부분인것 같습니다. 특별한 기준은 없었고 `final`을 선언하지 않는 방향으로 통일할 것 같아요!

2020-05-19 09:31 UTC, beginin15 commented on BE/src/main/java/com/codesquad/sidedish/dao/ProductDAO.java
> +                }
`RowMapper`를 상속받은 클래스를 따로 정의해서 해당 클래스에 `@Configuration`을 붙이는 방법을 말씀하시는 걸까요?

2020-05-19 09:41 UTC, beginin15 commented
리뷰 감사합니다! 피드백을 받고 개선하는 것이 중요한 건데 구현에 쫓기다 보니 이전 프로젝트를 잘 챙겨보지 못했네요 ㅠㅠ